# Пример генерации моделей

В данном примере показано, как с помощью программного интерфейса (API) можно обучить генеративную модель и использовать ее для генерации модели СКФС. В качестве прикладной области используются модели предприятий, основанные на публичном наборе данных SAP-SAM.

In [1]:
import sys
# Для загрузки модулей из основного каталога OrGAN,
# который находится в родительском каталоге
sys.path.insert(0, '..')

from organ.solver import Solver
from organ.config import make_config
from organ.demo import SapSamEMStructureModel

In [2]:
import os
import random
import numpy as np

## Обучение модели

Обучение выполняется с использованием аугментированного набора, размещенного в каталоге 'demo_data/sapsam_aug'.

Промежуточные результаты обучения сохраняются в каталоге 'output/models_sapsam' каждые 500 итераций обучения.

Обучение прекращается после 4000 итераций.

In [3]:
config = make_config(
    rules=SapSamEMStructureModel(),
    data_dir='../demo_data/sapsam_aug',
    conditional=False,
    parametric=False,
    model_save_dir='../output/models_sapsam',
    log_dir='../output/logs_sapsam',
    model_save_step=500,
    num_iters=4000,
)

# Create directories if not exist.
if not os.path.exists(config.log_dir):
    os.makedirs(config.log_dir)
if not os.path.exists(config.model_save_dir):
    os.makedirs(config.model_save_dir)
if config.samples_dir is not None and \
        not os.path.exists(config.samples_dir):
    os.makedirs(config.samples_dir)

os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"]="1"    
    
solver = Solver(config)
solver.train()

Max nodes: 22
Node types: 22 22
Edge types: 2 2
EdgeAwareGenerator(
  (layers): Sequential(
    (0): Linear(in_features=8, out_features=128, bias=True)
    (1): Tanh()
    (2): Dropout(p=0.0, inplace=True)
    (3): Linear(in_features=128, out_features=256, bias=True)
    (4): Tanh()
    (5): Dropout(p=0.0, inplace=True)
    (6): Linear(in_features=256, out_features=512, bias=True)
    (7): Tanh()
    (8): Dropout(p=0.0, inplace=True)
  )
  (edges_ctx_layer): Linear(in_features=512, out_features=32, bias=True)
  (edge_layers): Sequential(
    (0): Linear(in_features=54, out_features=128, bias=True)
    (1): Tanh()
    (2): Linear(in_features=128, out_features=64, bias=True)
    (3): Tanh()
    (4): Linear(in_features=64, out_features=32, bias=True)
    (5): Tanh()
  )
  (edges_layer): Linear(in_features=32, out_features=2, bias=True)
  (nodes_layer): Linear(in_features=512, out_features=22, bias=True)
  (dropout): Dropout(p=0.0, inplace=False)
)
G
The number of parameters: 210904
Discri

/home/tnn/OrGAN/organ/solver.py:795: RuntimeWarning: Mean of empty slice.
  for k, v in m0.items()}
/usr/local/lib/python3.6/dist-packages/numpy/core/_methods.py:161: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)


Elapsed [0:00:01], Iteration [40/4000], D/loss_real: 0.6766, D/loss_fake: 0.7960, V/loss: 0.8966, G/loss_fake: 0.6019, G/loss_value: 0.0568, G/loss_soft: 0.0000, Sample score: nan, node score: 0.9000, edge score: 0.0000, Accuracy: 0.0000
Elapsed [0:00:01], Iteration [50/4000], D/loss_real: 0.6737, D/loss_fake: 0.7515, V/loss: 0.8558, G/loss_fake: 0.6386, G/loss_value: 0.0831, G/loss_soft: 0.0000, Sample score: nan, node score: 1.0000, edge score: 0.0000, Accuracy: 0.0000
Elapsed [0:00:01], Iteration [60/4000], D/loss_real: 0.6685, D/loss_fake: 0.7203, V/loss: 0.8049, G/loss_fake: 0.6669, G/loss_value: 0.1215, G/loss_soft: 0.0000, Sample score: nan, node score: 1.0000, edge score: 0.0000, Accuracy: 0.0000
Elapsed [0:00:01], Iteration [70/4000], D/loss_real: 0.6509, D/loss_fake: 0.6792, V/loss: 0.7373, G/loss_fake: 0.7074, G/loss_value: 0.1830, G/loss_soft: 0.0000, Sample score: nan, node score: 1.0000, edge score: 0.0000, Accuracy: 0.0000
Elapsed [0:00:02], Iteration [80/4000], D/loss_r

## Генерация моделей СКФС

Генерация выполняется с использованием модели, обученной на 4000 итераций и размещенной в каталоге 'demo_data/sapsam_aug'.

In [4]:
config.test_iters = 4000
solver_g = Solver(config)
orgs = solver_g.generate_valid(10)

Max nodes: 22
Node types: 22 22
Edge types: 2 2
EdgeAwareGenerator(
  (layers): Sequential(
    (0): Linear(in_features=8, out_features=128, bias=True)
    (1): Tanh()
    (2): Dropout(p=0.0, inplace=True)
    (3): Linear(in_features=128, out_features=256, bias=True)
    (4): Tanh()
    (5): Dropout(p=0.0, inplace=True)
    (6): Linear(in_features=256, out_features=512, bias=True)
    (7): Tanh()
    (8): Dropout(p=0.0, inplace=True)
  )
  (edges_ctx_layer): Linear(in_features=512, out_features=32, bias=True)
  (edge_layers): Sequential(
    (0): Linear(in_features=54, out_features=128, bias=True)
    (1): Tanh()
    (2): Linear(in_features=128, out_features=64, bias=True)
    (3): Tanh()
    (4): Linear(in_features=64, out_features=32, bias=True)
    (5): Tanh()
  )
  (edges_layer): Linear(in_features=32, out_features=2, bias=True)
  (nodes_layer): Linear(in_features=512, out_features=22, bias=True)
  (dropout): Dropout(p=0.0, inplace=False)
)
G
The number of parameters: 210904
Discri

## Отображение результата генерации

In [14]:
print('Подразделения:\n', orgs[0].nodes)
for node in orgs[0].nodes:
    if node > 0:
        print("Подразделение ", node, ": ", config.rules.node_type_dict[node]["title"])
print('Связи:\n', orgs[0].edges)

i = 0
for edge_row in orgs[0].edges:
    j = 0
    for edge_val in edge_row:
        if edge_val > 0:
            print("Связь (", i, ", ", j, ") от ", 
                  config.rules.node_type_dict[i]["title"], " к ", config.rules.node_type_dict[j]["title"]
                 )
        j += 1
    i += 1

Подразделения:
 [0 1 2 0 4 5 0 0 0 9 0 0 0 0 0 0 0 0 0 0 0 0]
Подразделение  1 :  Managment
Подразделение  2 :  Sales
Подразделение  4 :  Finance
Подразделение  5 :  Logistics
Подразделение  9 :  Human Resources
Связи:
 [[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 